services:

  postgres:
    image: postgres:18
    container_name: product-service-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5434:5432"

    volumes:
      - product_service_postgres_data:/var/lib/postgresql/data

volumes:
  product_service_postgres_data: