spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5434/product_db
    username: samar
    password: samar

    jpa:
      hibernate:
        ddl-auto: validate

    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
