spring:
  application:
    name: product-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/product_db}
    username: ${POSTGRES_USER:samar}
    password: ${POSTGRES_PASSWORD:samar}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

bugsnag:
  api-key: ${BUGSNAG_API_KEY:}

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG